spring:
  application:
    name: stopbell-backend
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  issuer: stopbell
  access-token-expiration: PT1H

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
