spring:
  application:
    name: stopbell-backend
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
